name: anker-discord-bot CI

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install
      run: yarn install
    - name: add global ts-node
      run: yarn global add typescript ts-node
    - name: test
      run: yarn test
    - name: build
      run: yarn build
