name: anker-discord-bot CI

on: [push]

jobs:
  build:

    name: windows CI
    
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: install
      run: yarn install
    - name: test
      run: yarn test
    - name: build
      run: yarn build
    - name: upload
      uses: actions/upload-artifact@v1
      with:
        name: anker-discord-bot
        path: dist
