name: anker-discord-bot CI

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install
      run: yarn install
    - name: build
      run: yarn build
    - name: install ts-node again
      run: yarn install ts-node
    - name: test
      run: yarn test
